### ISSUE TITLE
findViewById used instead of binding in MainActivity

### ISSUE THREAD

**Issue by rajitdeb** [danascape/robust#3]
findViewById is used instead of binding in MainActivity which is unnecessary. findViewById can be removed and binding can be used to achieve the same functionality but with better optimization @danascape

**Comment by rajitdeb** [comment]
Please label this issue as "good first issue" and "hacktoberfest".

**Comment by rajitdeb** [comment]
I can work on this issue, please assign this issue to me @danascape

**Comment by danascape** [comment]
yea sure, feel free to drop a PR
